/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppEquipmentRouteImport } from './routes/_app/equipment'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrewRouteImport } from './routes/_app/crew'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings.users'
import { Route as AppSettingsProfilesRouteImport } from './routes/_app/settings.profiles'
import { Route as AppProjectsTemplatesRouteImport } from './routes/_app/projects.templates'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewRoute = AppCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfilesRoute = AppSettingsProfilesRouteImport.update({
  id: '/settings/profiles',
  path: '/settings/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsTemplatesRoute = AppProjectsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/crew': typeof AppCrewRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipment': typeof AppEquipmentRoute
  '/invoices': typeof AppInvoicesRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/templates': typeof AppProjectsTemplatesRoute
  '/settings/profiles': typeof AppSettingsProfilesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/crew': typeof AppCrewRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipment': typeof AppEquipmentRoute
  '/invoices': typeof AppInvoicesRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/projects/$id': typeof AppProjectsIdRoute
  '/projects/templates': typeof AppProjectsTemplatesRoute
  '/settings/profiles': typeof AppSettingsProfilesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/crew': typeof AppCrewRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/projects/templates': typeof AppProjectsTemplatesRoute
  '/_app/settings/profiles': typeof AppSettingsProfilesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/calendar'
    | '/crew'
    | '/dashboard'
    | '/equipment'
    | '/invoices'
    | '/projects'
    | '/projects/$id'
    | '/projects/templates'
    | '/settings/profiles'
    | '/settings/users'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/calendar'
    | '/crew'
    | '/dashboard'
    | '/equipment'
    | '/invoices'
    | '/projects'
    | '/projects/$id'
    | '/projects/templates'
    | '/settings/profiles'
    | '/settings/users'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/_app/calendar'
    | '/_app/crew'
    | '/_app/dashboard'
    | '/_app/equipment'
    | '/_app/invoices'
    | '/_app/projects'
    | '/_app/projects/$id'
    | '/_app/projects/templates'
    | '/_app/settings/profiles'
    | '/_app/settings/users'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew': {
      id: '/_app/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AppCrewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profiles': {
      id: '/_app/settings/profiles'
      path: '/settings/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AppSettingsProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/templates': {
      id: '/_app/projects/templates'
      path: '/templates'
      fullPath: '/projects/templates'
      preLoaderRoute: typeof AppProjectsTemplatesRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsTemplatesRoute: typeof AppProjectsTemplatesRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsTemplatesRoute: AppProjectsTemplatesRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCrewRoute: typeof AppCrewRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsProfilesRoute: typeof AppSettingsProfilesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCrewRoute: AppCrewRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsProfilesRoute: AppSettingsProfilesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
